var c=document.getElementById('gameCanvas');var ctx=c.getContext('2d');var W=240,H=282;
var state='title',songIdx=0,score=0,combo=0,maxCombo=0,perfect=0,good=0,miss=0;
var notes=[],activeNotes=[],frame=0,songTime=0,bpm=140,spb=60/140;
var LANES=3,LANE_W=W/LANES,HIT_Y=H-40,NOTE_SPEED=3;
var COLORS=['#FF006E','#00F5D4','#FEE440'];
var hitFx=[],msg='',msgT=0;
var songs=[{name:'Neon Pulse',bpm:140,notes:[{t:0.40,l:0},{t:0.85,l:1},{t:1.30,l:2},{t:1.75,l:0},{t:2.20,l:1},{t:2.65,l:2},{t:3.10,l:0},{t:3.55,l:1},{t:4.00,l:2},{t:4.45,l:0},{t:4.90,l:1},{t:5.35,l:2},{t:5.80,l:0},{t:6.25,l:1},{t:6.70,l:2},{t:7.15,l:0},{t:7.60,l:1},{t:8.05,l:2},{t:8.50,l:0},{t:8.95,l:1},{t:9.40,l:2},{t:9.85,l:0},{t:10.30,l:1},{t:10.75,l:2},{t:11.20,l:0},{t:11.65,l:1},{t:12.10,l:2},{t:12.55,l:0},{t:13.00,l:1},{t:13.45,l:2},{t:13.90,l:0},{t:14.35,l:1},{t:14.80,l:2},{t:15.25,l:0},{t:15.70,l:1},{t:16.15,l:2},{t:16.60,l:0},{t:17.05,l:1},{t:17.50,l:2},{t:17.95,l:0},{t:18.40,l:1},{t:18.85,l:2},{t:19.30,l:0},{t:19.75,l:1},{t:20.20,l:2},{t:20.65,l:0},{t:21.10,l:1},{t:21.55,l:2},{t:22.00,l:0},{t:22.45,l:1},{t:22.90,l:2},{t:23.35,l:0},{t:23.80,l:1},{t:24.25,l:2},{t:24.70,l:0},{t:25.15,l:1},{t:25.60,l:2},{t:26.05,l:0},{t:26.50,l:1},{t:26.95,l:2},]}];
function startSong(idx){songIdx=idx;var s=songs[idx];bpm=s.bpm;spb=60/bpm;activeNotes=[];for(var i=0;i<s.notes.length;i++){activeNotes.push({t:s.notes[i].t,l:s.notes[i].l,hit:false,y:-10});}score=0;combo=0;maxCombo=0;perfect=0;good=0;miss=0;frame=0;songTime=0;hitFx=[];state='play';}
function tryHit(lane){var best=-1,bestD=999;for(var i=0;i<activeNotes.length;i++){var n=activeNotes[i];if(n.l===lane&&!n.hit){var d=Math.abs(n.y-HIT_Y);if(d<bestD){bestD=d;best=i;}}}if(best>=0&&bestD<40){activeNotes[best].hit=true;if(bestD<15){perfect++;score+=100+combo*10;hitFx.push({x:lane*LANE_W+LANE_W/2,y:HIT_Y,t:20,c:'#00F5D4',txt:'PERFECT'});}else{good++;score+=50+combo*5;hitFx.push({x:lane*LANE_W+LANE_W/2,y:HIT_Y,t:20,c:'#FEE440',txt:'GOOD'});}combo++;if(combo>maxCombo)maxCombo=combo;}}
function drawTitle(){ctx.fillStyle='#0a0a2e';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#FF006E';ctx.font='bold 22px sans-serif';ctx.fillText('GHOST TAP',W/2,80);ctx.fillStyle='#00F5D4';ctx.font='bold 18px sans-serif';ctx.fillText('GROOVE',W/2,105);ctx.fillStyle='#FEE440';ctx.font='10px sans-serif';ctx.fillText('HARD MODE',W/2,135);var a=0.5+0.5*Math.sin(frame*0.05);ctx.fillStyle='rgba(255,255,255,'+a+')';ctx.font='12px sans-serif';ctx.fillText('TAP TO START',W/2,200);frame++;}
function drawGame(){ctx.fillStyle='#0a0a1a';ctx.fillRect(0,0,W,H);for(var i=1;i<LANES;i++){ctx.strokeStyle='#222';ctx.beginPath();ctx.moveTo(i*LANE_W,0);ctx.lineTo(i*LANE_W,H);ctx.stroke();}ctx.fillStyle='rgba(255,255,255,0.1)';ctx.fillRect(0,HIT_Y-5,W,10);for(var i=0;i<LANES;i++){ctx.strokeStyle=COLORS[i];ctx.lineWidth=2;ctx.beginPath();ctx.arc(i*LANE_W+LANE_W/2,HIT_Y,12,0,Math.PI*2);ctx.stroke();ctx.lineWidth=1;}
for(var i=0;i<activeNotes.length;i++){var n=activeNotes[i];if(!n.hit&&n.y>-20&&n.y<H+20){ctx.fillStyle=COLORS[n.l];ctx.beginPath();ctx.arc(n.l*LANE_W+LANE_W/2,n.y,10,0,Math.PI*2);ctx.fill();}}for(var i=hitFx.length-1;i>=0;i--){var f=hitFx[i];ctx.fillStyle=f.c;ctx.font='bold 10px sans-serif';ctx.textAlign='center';ctx.fillText(f.txt,f.x,f.y-20+f.t);f.t--;if(f.t<=0)hitFx.splice(i,1);}
ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.textAlign='left';ctx.fillText('Score:'+score,5,15);ctx.textAlign='right';ctx.fillText('Combo:'+combo,W-5,15);ctx.textAlign='center';}
function drawResults(){ctx.fillStyle='#0a0a2e';ctx.fillRect(0,0,W,H);ctx.fillStyle='#FF006E';ctx.font='bold 18px sans-serif';ctx.fillText('RESULTS',W/2,40);ctx.fillStyle='#fff';ctx.font='12px sans-serif';ctx.fillText('Score: '+score,W/2,80);ctx.fillText('Perfect: '+perfect,W/2,100);ctx.fillText('Good: '+good,W/2,120);ctx.fillText('Miss: '+miss,W/2,140);ctx.fillText('Max Combo: '+maxCombo,W/2,160);var pct=Math.round((perfect+good)/(perfect+good+miss)*100)||0;ctx.fillStyle='#FEE440';ctx.font='bold 14px sans-serif';ctx.fillText(pct+'%',W/2,190);var a=0.5+0.5*Math.sin(frame*0.05);ctx.fillStyle='rgba(255,255,255,'+a+')';ctx.font='10px sans-serif';ctx.fillText('TAP TO RESTART',W/2,230);frame++;}
function gameLoop(){if(state==='title'){drawTitle();}else if(state==='play'){songTime+=1/60;for(var i=0;i<activeNotes.length;i++){var n=activeNotes[i];if(!n.hit){n.y=HIT_Y-(n.t-songTime)*NOTE_SPEED*60;if(n.y>H+30&&!n.hit){n.hit=true;miss++;combo=0;}}}var allDone=true;for(var i=0;i<activeNotes.length;i++){if(!activeNotes[i].hit){allDone=false;break;}}if(allDone){state='results';}drawGame();}else if(state==='results'){drawResults();}requestAnimationFrame(gameLoop);}
c.addEventListener('click',function(e){if(state==='title'){startSong(0);return;}if(state==='results'){state='title';return;}var x=e.offsetX||e.layerX||0;var lane=Math.floor(x/LANE_W);if(lane>=0&&lane<LANES)tryHit(lane);});
c.addEventListener('touchstart',function(e){e.preventDefault();if(state==='title'){startSong(0);return;}if(state==='results'){state='title';return;}var t=e.touches[0];var r=c.getBoundingClientRect();var x=t.clientX-r.left;var lane=Math.floor(x/LANE_W);if(lane>=0&&lane<LANES)tryHit(lane);},{passive:false});
window.addEventListener('scrollUp',function(){if(state==='play')tryHit(0);else if(state==='title')startSong(0);else state='title';});
window.addEventListener('scrollDown',function(){if(state==='play')tryHit(2);else if(state==='title')startSong(0);else state='title';});
window.addEventListener('sideClick',function(){if(state==='play')tryHit(1);else if(state==='title')startSong(0);else state='title';});
document.addEventListener('keydown',function(e){if(e.key==='a'||e.key==='ArrowLeft'){if(state==='play')tryHit(0);else if(state!=='play'){if(state==='title')startSong(0);else state='title';}}if(e.key==='s'||e.key==='ArrowDown'){if(state==='play')tryHit(1);else if(state!=='play'){if(state==='title')startSong(0);else state='title';}}if(e.key==='d'||e.key==='ArrowRight'){if(state==='play')tryHit(2);else if(state!=='play'){if(state==='title')startSong(0);else state='title';}}});
gameLoop();

